### ISSUE TITLE
What the heck - firefox path?

### ISSUE THREAD

**Issue by erichfrazer** [hbenl/vscode-firefox-debug#58] opened 2018-01-09 20:28 UTC
I'm a pretty seasoned developer, but I'm not understanding how, in VSCode, it's supposed to know where to find firefox in order to launch it. When I try to launch the debugger using your plugin, a not very helpful message shows up "Couldn't find the firefox executable. Please specify the path in your launch configuration." HOW DO I DO THAT? No instructions on how to set the firefox path! Firefox is installed on my machine, 64 bit version, at /users/(me)/AppData/Local/Mozilla Firefox/Firefox.exe. 

I've followed the instructions to start firefox in debug mode from the command line... Unrelated, but I'll ask anyhow: Why is it when I start Firefox this way, I can not open up any other hyperlinks on my system? They say, "firefox is busy and cannot open, close it or try again". Lame.

**Comment by hbenl** [comment] 2018-01-10 17:58
The debug adapter looks for the Firefox executable in the standard install location, if it's installed in a different location, you have to use the `firefoxExecutable` property in your `launch.json`. This is mentioned (although not very prominently) in the documentation section ["Further optional configuration properties"](https://github.com/hbenl/vscode-firefox-debug#further-optional-configuration-properties).
I will try to make the error message more informative.

**Comment by hbenl** [comment] 2018-01-10 18:00
> Why is it when I start Firefox this way, I can not open up any other hyperlinks on my system?

That's odd, I have not experienced this behaviour. I'll see if I can reproduce it.

**Comment by jnachtigall** [comment] 2018-01-11 11:06
> Why is it when I start Firefox this way, I can not open up any other hyperlinks on my system?

I guess this comes from `-no-remote`:
https://github.com/hbenl/vscode-firefox-debug/blame/a7e5ef2826ea07f9bc5b36868742be35c3ddd4fe/README.md#L101-L113

(I cannot link the the README.md file in a normal way, hence the `blame` view as a workaround)

@hbenl I was coming across the same issue and I removed this flag when starting firefox. I think it would be better to remove the `no-remote` from the README. What you think?

Also when checking the README of Chrome Debugger I saw that they recommend to change the properties of the starter (and command line execution is only a second recommendation):

https://github.com/Microsoft/vscode-chrome-debug/blame/master/README.md#L82-L85

I think if the Firefox Adapter could add a similar recommendation in the README it would also help to getting started.

**Comment by agathver** [comment] 2018-01-23 06:06
Just had this situation in Linux, so opened a PR #59 that makes it looks inside all folders under `PATH`. (For *NIX only)

**Comment by hbenl** [comment] 2018-01-23 18:46
@erichfrazer I've tried to make the error message more helpful.

@jnachtigall Thanks for pointing me to `-no-remote`, I'm pretty sure this used to work at some point for launching multiple independent Firefox processes, but now it seems to be just broken. I've removed it from the documentation.

@agathver Good idea, thanks for the PR (which I have just merged)

**Closed by hbenl** 2018-01-23 18:46 UTC
