### ISSUE TITLE
Debug console should receive `console` logs

### ISSUE THREAD

**Issue by blackwind** [hbenl/vscode-firefox-debug#28] opened 2017-01-24 03:53 UTC
It would be helpful if `console.log()`, `console.warn()`, `console.error()`, et al, would output to VSCode's debug console. Currently, at least with my Add-on SDK add-on, the debug console is pointless, as nothing is ever written to it.

**Comment by hbenl** [comment] 2017-01-24 12:14
I just published a fix for this.

Note that I had to redirect Firefox' `stdout` to the debug console for this, and this also includes internal Firefox error messages (I sometimes get a lengthy error message immediately after starting Firefox). Since I can't think of a reliable way to distinguish add-on console messages from these internal Firefox error messages, I couldn't filter them out.

**Closed by hbenl** 2017-01-24 12:14 UTC

**Comment by blackwind** [comment] 2017-01-24 22:13
Thanks for the quick fix!

**Comment by blackwind** [comment] 2017-04-29 22:48
Somewhere along the line, this broke again. All I see in the current release are expandable "Error" nodes when an error occurs.

**Comment by hbenl** [comment] 2017-05-01 11:27
Unfortunately it only works if you don't set `reAttach` to `true`. The problem is that add-ons built with `jpm` send their console messages to Firefox' `stdout` and I can't attach to that if Firefox is running detached (which is necessary for `reAttach`). The only fix that I can think of is to write a node.js proxy that is launched together with Firefox and relays Firefox' `stdout` to a local TCP socket (to which the debug adapter can then attach). But that is low priority for me.
