### ISSUE TITLE
Breakpoint not loading in VS Code with Firefox Dev Edition (66)

### ISSUE THREAD

**Issue by kmonchamp** [hbenl/vscode-firefox-debug#98] opened 2019-02-10 00:01 UTC
Firefox Developer Edition 66.0b6, VS Code 1.31, on Linux

I created a quick test app, using create-react-app --typescript. I am able to set and have verified breakpoints. When the breakpoint is hit in the app, FF pauses the app, but VS Code never loads the breakpoint data/stack and I am unable to continue execution without a reload. Switching the launch configuration to use current stable Firefox (65) everything works fine. 

My launch config is:
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Firefox",
      "type": "firefox",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": "client",
      "reAttach": true,
      "keepProfileChanges": true,
      "firefoxExecutable": "/usr/bin/firefox",
      //"firefoxExecutable": "/usr/bin/firefox-developer-edition",
      "profileDir": "${workspaceFolder}/FFDevProfile",
      "skipFiles": ["${workspaceFolder}/node_modules/**", "http?(s):/**"],
      "pathMappings": [
        {
          "url": "webpack-internal:///",
          "path": "/"
        },
        {
          "url": "http://localhost:3000/",
          "path": "/"
        }
      ],
      "log": {
        "fileName": "${workspaceFolder}/log.txt",
        "fileLevel": {
          "default": "Debug"
        }
      }
    }
  ]
}

I ran the app with a breakpoint set. First in Firefox Dev Edition and then in Firefox stable.
Log file is in gist due to size https://gist.github.com/kmonchamp/7f4d37c4c5f6762c8f50baf46b20bdfa

**Comment by hbenl** [comment] 2019-02-11 19:29
This was caused by a change to the debug protocol in Firefox 66.
It's fixed in version 1.7.6 (which I just published).

**Closed by hbenl** 2019-02-11 19:29 UTC

**Comment by kmonchamp** [comment] 2019-02-11 20:32
Thanks, this is working for me now.
