### ISSUE TITLE
Debug addon's

### ISSUE THREAD

**Issue by GitStorageOne** [hbenl/vscode-firefox-debug#47] opened 2017-08-29 20:14 UTC
Hello!
Seems, addon debugging works not as expected.
I can successfully connect and debug addon (type: "webExtension") from firefox
![moz-connect-opts](https://user-images.githubusercontent.com/3978064/29842425-7fc97de8-8d11-11e7-9fc3-60a4d0a6b9fe.PNG)
Firefox - Developer - connect - 127.0.0.1 port 6000, while connection, firefox checks not only available tabs, but also addons. vscode extension requesting only tabs.
vscode debugger request:
![vsc](https://user-images.githubusercontent.com/3978064/29841591-a4b72f22-8d0e-11e7-82d8-ea400b1a35be.PNG)
mozilla debugger request:
![moz](https://user-images.githubusercontent.com/3978064/29841599-aa018a36-8d0e-11e7-9fa0-0e09e5f80a89.PNG)

I can provide executable application that will help you investigate issue, if you want.
Application use spidermonkey and available for debugging as addon with type "webExtension".

**Comment by hbenl** [comment] 2017-08-30 10:02
Please attach your `launch.json`. Also, a debug log could be useful: add
```json
    "log": {
        "fileName": "${workspaceRoot}/vscode-firefox-debug.log",
        "fileLevel": {
            "default": "Debug"
        }
    }
```
to your launch configuration and start a debug session. Afterwards, there should be a file called `vscode-firefox-debug.log` in your project folder. Please attach that to this issue as well.

**Comment by GitStorageOne** [comment] 2017-08-30 10:16
Here is requested files (as txt, git not allows json)
[launch.json.txt](https://github.com/hbenl/vscode-firefox-debug/files/1263216/launch.json.txt)
[vscode-firefox-debug.txt](https://github.com/hbenl/vscode-firefox-debug/files/1263219/vscode-firefox-debug.txt)

**Comment by hbenl** [comment] 2017-08-30 18:46
Interesting, I had never heard of SyNode before. The reason this doesn't work is that this debug adapter wants to install the addon before requesting `listAddons` to find and attach to the addon. To install the addon it needs the name of an "addonsActor", which is usually contained in the `listTabs` response. SyNode doesn't specify this, so that's where the debug adapter gets stuck. 

I have created a variant of the debug adapter and attached it here. This variant will recognize when it is connected to SyNode and in this case tries to attach to the addon without installing it first.
[vscode-firefox-debug-0.15.4-synode.zip](https://github.com/hbenl/vscode-firefox-debug/files/1264699/vscode-firefox-debug-0.15.4-synode.zip)
To install this variant, you first have to change the file extension from `.zip` to `.vsix` (Github refuses vsix files) and then use the "Install from VSIX..." menu option in VS Code (you may have to uninstall the 
debug adapter that was installed from the Marketplace first).

I have also pushed the `synode` branch containing the variant to this repository. If you want to work on this yourself:
* Clone this repository and checkout the `synode` branch
* `npm install` installs the dependencies
* `npm run build` builds the debug adapter
* `npm run package` creates the vsix package that you can then install in VS Code

**Comment by GitStorageOne** [comment] 2017-08-30 20:13
Hello! Thanks for response.

SyNode is open source spidermonkey port to delphi, part of [mORMot framework](https://synopse.info/files/html/Synopse%20mORMot%20Framework%20SAD%201.18.html).
The reason why i post here is that firefox actually can debug app, and regarding on log, i see that vscode addon almost done that job too, almost.

I tested new debug plugin, now see that plugin requesting addons and receiving list.
But seems, not trying to connect.
[vscode-firefox-debug.txt](https://github.com/hbenl/vscode-firefox-debug/files/1264868/vscode-firefox-debug.txt)

I'll do everything what i can, but if you would like to try beat the issue (i'm sure, you can do it very quickly, with working test app. Unfortunately, i'm not familiar with vscode plugin territory(( )
Anyway, [here is source and exe](https://drive.google.com/open?id=0ByjqYkfEqb0ORDJ4cHVMeGROdVU). From \win64\bin\ directory possible to run app and it immediately ready for debugging at port 6000. "win64\node.apps\app1\" is home directory of "addon", where .vscode folder present.
That folder can be opened from vscode and all required configs (include launch.json) already there.

**Comment by GitStorageOne** [comment] 2017-08-30 20:54
![addonmanager ts](https://user-images.githubusercontent.com/3978064/29894570-713326da-8dde-11e7-9f30-7586048e57eb.PNG)
"this" - undefined here, while left side contain value.

**Comment by GitStorageOne** [comment] 2017-08-30 21:14
How to avoid message like that?
> PathConversion: Can't convert url P:\Win64\node.apps\app1\lib\index.js to path

**Comment by GitStorageOne** [comment] 2017-08-31 08:02
Updated source and exe, now with all changes (include temporary) possible to debug index.js from "Win64\node.apps\app1\lib" folder, but virtual sources not available (global sources without files) and can't see list of loaded sources.

**Comment by hbenl** [comment] 2017-08-31 16:44
* you don't need to replace the if statement with `if (true)` - `this` is actually **not** `undefined`, the display of the VS Code node debugger seems to be buggy here. What you actually need to do is set your addon id to `server1.conn1.addon0` in your `manifest.json`
* to convert the "urls" that SyNode sends (which are actually not urls but paths), you can add `pathMappings` to your `launch.json` like this:
```
            "pathMappings": [
                {
                    "url": "P:",
                    "path": "p:"
                }
            ]
```
* Unlike Firefox, SyNode doesn't send `newSource` events for sources that were loaded by SyNode before the debugger was attached. I have pushed a workaround for that to the `synode` branch.
* this debug adapter isn't able to show all the loaded sources yet - but that's the feature that I am currently working on :) I hope to finish it within a week or so.

My impression of the SyNode implementation of the debug protocol is that it is just enough to get it to work with the Firefox debugger, but since this debug adapter doesn't always work exactly the same as the Firefox debugger, I expect there to be more obstacles...

**Comment by GitStorageOne** [comment] 2017-08-31 19:39
> server1.conn1.addon0

[Addon id](https://developer.mozilla.org/ru/Add-ons/WebExtensions/manifest.json) not same as actor.
addon id should be same for all debug threads (SyNode can start multiple threads with same addon), while actor representing thread.
Here is current response to ListAddons request from test app:
{
    "from": "root",
    "addons": [
        {
            "actor": "server1.conn1.addon0",
            "id": "server1.conn1.addon0",
            "name": "app1",
            "url": "server1.conn1.addon0",
            "debuggable": true,
            "consoleActor": "console0"
        }
    ]
}
[I searched for documentation for this structure](http://searchfox.org/mozilla-central/source/devtools/docs/backend/protocol.md) (how to fill it correctly), did't found.
Do you know where to read?
Here i see possibly incorrect data in `id` and `url` fields. 
I guess that `id` should be `"app1"` (same as `id` from manifest) and `url` something like `"file:///P:/Win64/node.apps/app1/lib/"`

I will play with values. If you have useful links to Mozilla debug protocol, i would be appreciated.

**Comment by hbenl** [comment] 2017-08-31 21:39
Yes, the addon id is *usually* not identical with the actor name, but in SyNode's implementation of the debug protocol they are identical. You can see this in the response to `listAddons`: the `actor` property specifies the name of the actor for the addon and the `id` property specifies the id of the addon - and in this response they are the same. I don't use the `url` field in my debug adapter and don't remember what it's for. But the strange values in this response show that SyNode's implementation of the debug protocol is very different from Firefox's...
The only documentation for the protocol that I know is the one you also linked to. It's *very* incomplete and even wrong in some places. So I often had to reverse engineer the protocol by capturing the communication between Firefox and the (remotely attached) Firefox debugger with Wireshark. Recently I also dug into Firefox's source code to find out more about the protocol.

**Comment by GitStorageOne** [comment] 2017-09-01 12:32
> Yes, the addon id is usually not identical with the actor name

Since SyNode is open source, i can try implement some changes.
ListAddons response, source response. Let you know when will get proper results.

**Comment by GitStorageOne** [comment] 2017-09-02 00:24
Hello!
Updated [source and exe](https://drive.google.com/open?id=0ByjqYkfEqb0ORDJ4cHVMeGROdVU).
Now debugger works, actor name looks more beautiful. 
Some thing i hardcoded temporary for testing purposes. But, works! 

Next part, i see that source map not available. Is your debugger support source maps? 
May be synode not support source maps yet, not sure)

**Comment by hbenl** [comment] 2017-09-02 15:05
Yes, it looks like SyNode doesn't support source maps.
The good news is: Firefox is changing the way that source maps are handled by the debugger, they used to be handled on the server side of the debug protocol (i.e. Firefox or SyNode) but will be handled on the client side of the protocol (i.e. Firefox debugger or my debug adapter) in the future. I have already implemented this change in my debug adapter, to enable it just add `"sourceMaps": "client"` to your `launch.json`. However, there's one piece that's missing: detecting the `sourceMappingURL` is still done on the server side, i.e. SyNode should detect it and add a property `sourceMapURL` to the `Source` object it sends. The debug adapter will then read this property [here](https://github.com/hbenl/vscode-firefox-debug/blob/94df4b5c52428acf9d0a241d5b23996de4866333/src/firefox/sourceMaps/thread.ts#L76).

**Comment by GitStorageOne** [comment] 2017-09-04 10:43
Hello!
>However, there's one piece that's missing: detecting the sourceMappingURL is still done on the server side

What about line `//# sourceMappingURL=index.js.map`, when source map available, such line automatically added to output JS and may be used for automatic source map detection.

[Updated source and exe](https://drive.google.com/open?id=0ByjqYkfEqb0ORDJ4cHVMeGROdVU), now response field `sourceMapURL` present and filled for index.js source.
But in debugger i get message that source not seen yet (index.ts). [log.txt](https://github.com/hbenl/vscode-firefox-debug/files/1274380/log.txt)

**Comment by hbenl** [comment] 2017-09-04 17:44
> What about line //# sourceMappingURL=index.js.map, when source map available, such line automatically added to output JS and may be used for automatic source map detection.

Yes, that's what I meant: SyNode should detect this line and set `sourceMapURL` to the url found in that line (`index.js.map`). However, when I look at the `Source` objects I get from SyNode (by setting a breakpoint in `FirefoxDebugSession.attachSource`), I see that `sourceMapURL` is set to an empty string for all sources, including `index.js`.
![capture](https://user-images.githubusercontent.com/16060807/30035316-277ae4dc-91a9-11e7-894c-91e6134206c5.PNG)

**Comment by GitStorageOne** [comment] 2017-09-04 17:50
Does that results taken with latest exe from my previous post?

**Comment by hbenl** [comment] 2017-09-04 18:17
Yes, and I just re-checked: when I try the same with the previous exe, `sourceMapURL` isn't set at all (not even to an empty string).

**Comment by GitStorageOne** [comment] 2017-09-05 19:44
Changed code, now SyNode source response looks like:
```
{
    "from": "thread",
    "type": "newSource",
    "source": {
        "actor": "source.15",
        "url": "file://P:/Win64/node.apps/app1/lib/index.js",
        "addonPath": "",
        "addonID": "app1",
        "isBlackBoxed": false,
        "isPrettyPrinted": false,
        "introductionUrl": null,
        "sourceMapURL": "index.js.map"
    }
}
```

Is it fine?
[Here is updated source and exe.](https://drive.google.com/open?id=0ByjqYkfEqb0ORDJ4cHVMeGROdVU)

**Comment by GitStorageOne** [comment] 2017-09-06 10:26
Interesting behavior :)
https://repl.it/KkFg/0

**Comment by GitStorageOne** [comment] 2017-09-06 13:03
[Here is updated source and exe.](https://drive.google.com/open?id=0ByjqYkfEqb0ORDJ4cHVMeGROdVU)

**Comment by hbenl** [comment] 2017-09-06 18:39
Yes, that is correct (and I am aware of the possibility that the `sourceMapURL` may contain the actual source map, this is already supported).
The next problem was a little bug in my implementation of client-side source maps. I fixed it and pushed the fix to the `synode` branch. Another problem was the `pathMappings` property in your `launch.json`, you should simply remove it!
Now I can set breakpoints in `index.ts`:
![capture2](https://user-images.githubusercontent.com/16060807/30128441-feda0210-9342-11e7-8ac6-2c3ab6997132.PNG)
However, the SyNode exe seems to be unstable: after a while, it always stops responding to the requests that it gets from the debug adapter.

**Comment by GitStorageOne** [comment] 2017-09-06 19:53
**That's so cool!** 
About stability - that's can be fixed, first step was get it work with your debugger.
Next step - tests with multiple threads (when multiple addons will be returned), that's take some time.

By the way, i found that even without line `//# sourceMappingURL=index.js.map` js debugging not work...

**Comment by hbenl** [comment] 2017-09-10 16:34
FYI: the latest release contains all fixes that I created on the `synode` branch, so you don't have to work with that branch anymore.

**Comment by GitStorageOne** [comment] 2017-09-10 16:37
👍, thanks.
> By the way, i found that even without line //# sourceMappingURL=index.js.map js debugging currently not work...
Is there was a bug?

**Comment by GitStorageOne** [comment] 2017-09-13 21:49
Hello!
I've prepared [new demo application](https://drive.google.com/open?id=0ByjqYkfEqb0ORDJ4cHVMeGROdVU). It much more functional and more stable.
Currently i see some issues with debugging, (with previous application too), while logs not showing any suspicious errors. If you can, please, check the demo.

**Comment by hbenl** [comment] 2017-09-15 15:23
Well, I checked it and just like the previous demo applications it freezes after a short while when I try to debug with VS Code:
![freeze](https://user-images.githubusercontent.com/16060807/30490534-8716ab1c-9a3a-11e7-84d4-61de58813f3c.png)

In fact, it sometimes freezes immediately after hitting a breakpoint. What I see in the logs is that the debug adapter sends a request (e.g. `DebugConnection: Sending request {"to":"frame.env.parent.parent.parent._grip0","type":"prototypeAndProperties"}`) and never receives a reply (in this example I'd expect something like `DebugConnection: Received response/event { ... "from": "frame.env.parent.parent.parent._grip0", ... }`)

As for the Loaded Scripts Explorer: SyNode doesn't need to do anything special, it already works! You'll find it at the bottom of the VS Code side pane:
![loadedscripts](https://user-images.githubusercontent.com/16060807/30490506-702b752c-9a3a-11e7-99bf-c14c648046e2.PNG)

**Comment by GitStorageOne** [comment] 2017-09-15 20:19
Can't freeze app.. Every time when app looks freezed i can press F5 in vscode after that app become normal again. Anyway i will investigate soon. I'm going to create demo app, while that i will catch issues on my side (but to develop app, your debugger is required, that's irreplaceable tool!).
Can you attach full response example for request type `prototypeAndProperties`?

Not entire demo app will be coded in typescript, some modules still will be in javascript.
So, need a way to seamless debug both TS and JS.
But, JS debugging for some reason not work (even when `sourceMapURL = ""`) :(
Can you confirm that?

About loaded scripts - when i select most of modules, there is no code available.
Is it limitation? Firefox can visualize all loaded modules (with functional breakpoints).
Seems firefox get sources remotely (firefox not require path to sources as well)
> 20170915 20042232 cust4 {"to":"source.11","type":"source"}
> 20170915 20042232 cust4 {"contentType":"text/javascript","source":{"type":"longString","initial":"(function (e ...

And about manifest.json - is it really required for debugger? 
It contain only app `Id`, i suppose debugger can use app `id` from `listAddons` response.. Isn't it?

**Comment by hbenl** [comment] 2017-09-17 18:16
> Every time when app looks freezed i can press F5 in vscode after that app become normal again.

OK, but it's not a real workaround because when you press F5 in VS Code, the debugger detaches for a short while and as a result, the app that you're debugging is resumed, so you lose your debugging state. Interestingly I just found that I can't make the app freeze under Windows 10, but it froze very frequently when I tried it on Windows 7.

> Can you attach full response example for request type prototypeAndProperties?

You can have a look at the `PrototypeAndPropertiesResponse` interface in `src/firefox/protocol.d.ts`. Anyway this request was just an example, usually SyNode sends a correct response to that request, but sometimes it froze after this or other requests.

> JS debugging for some reason not work

Yes, it doesn't work for me either. I think the problem is that currently the `Source` events have `addonID` set but not `addonPath`. If `addonID` is set then `addonPath` should contain the relative path of the file within the addon directory.
Also, `addonID` should _only_ be set for files that are in the addon directory, but not for all the SyNode internal files. And I would advise not to use the empty string for undefined values - if you want to say that some value is undefined then use javascript's `undefined` value or don't add the corresponding property to the object at all.

> About loaded scripts - when i select most of modules, there is no code available.

This is also a result of `addonID` being set for these files - the debug adapter tries to find files with no name (because `addonPath` is the empty string) within the addon directory.
Even without `addonID` being set for these files it may not work, because the files have urls that look like relative paths. Try to do the same thing that Firefox does for internal files: invent some url scheme for them (e.g. `synode://...`), then the debug adapter will understand that it has to fetch these files from SyNode with a `source` request instead of trying to find them in the file system.

**Comment by GitStorageOne** [comment] 2017-09-18 16:56
> but it froze very frequently when I tried it on Windows 7

That's why i can't reproduce, i use win10. Ok, will check later under win7 VM.

> If addonID is set then addonPath should contain the relative path of the file within the addon directory.
Also, addonID should only be set for files that are in the addon directory..

Done.

> Even without addonID being set for these files it may not work, because the files have urls that look like relative paths. Try to do the same thing that Firefox does for internal files: invent some url scheme for them (e.g. synode://...), then the debug adapter will understand that it has to fetch these files from SyNode with a source request instead of trying to find them in the file system.

I've found, that when url scheme is defined for internal modules, debugging not work.
Without `synode://` prefix, internal modules can be debugged without any problems.
Demo app from this message use `synode://` prefix for internal files, like you suggested.
Project also contain module `\Win64\core_modules\DevTools\Debugger_without_synode_prefix.js`, that can be renamed to `Debugger.js` - after that, `synode://` will disappear.
What do you think, should i just remove prefix or you have other ideas?)

I suppose, there is only last major unresolved issue left.
I changed web.app folder structure to be more realistic:

> lib
 -- index.js
 -- manifest.json
 -- index.js.map
 src
 -- index.ts
 -- index.d.ts

index.ts cannot be debugged when selected from project three, but perfectly debaggable when selected from loaded source three. Seems something with path comparing..

**Comment by hbenl** [comment] 2017-09-19 18:31
> I've found, that when url scheme is defined for internal modules, debugging not work.

I tracked this down to an issue with how VS Code handles urls for files opened from the Loaded Scripts Explorer (there are several issues in that area that still have to be fixed in VS Code). Since it does work without the `synode://` prefix, just remove that prefix.

> index.ts cannot be debugged when selected from project tree, but perfectly debuggable when selected from loaded source tree.

I couldn't reproduce that - it works perfectly for me in both cases. It may look like it's not working because breakpoints in `index.ts` only turn red after you have pressed the "Evaluate JS" button.

**Comment by GitStorageOne** [comment] 2017-09-21 16:33
> I couldn't reproduce that - it works perfectly for me in both cases

That's strange. Here is my steps (win10x64 10.0.15063, vscode 1.16.1 ia32):
1. Unpack archive to drive D:
2. Start "D:\mORMot_SyNode\RUN.bat"
3. Press button "Evaluate JS" (index.js is loaded)
4. Open folder "D:\mORMot_SyNode\Win64\web.apps\app1" with vscode.
5. Press F5 in vscode.
6. Open index.ts in vscode project tree and put breakpoint at line "19"

In debugger log i get:
```
DEBUG|013.839|BreakpointsAdapter: Setting 1 breakpoints for d:\mORMot_SyNode\Win64\web.apps\app1\src\index.ts
DEBUG|013.839|BreakpointsAdapter: Replying to setBreakpointsRequest (Source d:\mORMot_SyNode\Win64\web.apps\app1\src\index.ts not seen yet)
```
7. Close module in vscode and open loaded scripts list.
8. Select ../src/index.ts
9. Put breakpoint at line "19"
10. Everything OK, in debugger i get messages:
```
DEBUG|211.481|BreakpointsAdapter: Setting 1 breakpoints for d:\mORMot_SyNode\win64\web.apps\app1\src\index.ts
DEBUG|211.481|BreakpointsAdapter: Found source d:\mORMot_SyNode\win64\web.apps\app1\src\index.ts on tab thread
```

**Comment by hbenl** [comment] 2017-09-22 07:54
OK, I got it now.

> Seems something with path comparing..

Exactly. The issue is that you wrote `win64` in your `RUN.bat`, but the directory in the archive is called `Win64`. On Windows, paths are case insensitive, so this should work, but my debug adapter is case sensitive. I'll fix path comparisons to be case insensitive on Windows in the next release. Until then, you can fix this by replacing `win64` with`Win64` in your `RUN.bat`.

**Comment by GitStorageOne** [comment] 2017-10-02 12:50
Hi!
Found that when **internal** source placed in folder (for example `polyfill`), source request not happen:
`{"actor":"source.13","url":"polyfill/WindowTimer.js","isBlackBoxed":false,"isPrettyPrinted":false}`
> Replying to setBreakpointsRequest (Source polyfill\WindowTimer.js not seen yet)

**Comment by hbenl** [comment] 2017-10-15 11:59
Sorry for the delay. I just reproduced this and it's probably caused by Microsoft/vscode#32845.

> May be would be better to identify internal modules in same way as Node.js?

Well, I think that's probably a good idea, which is why I had proposed the `synode://` prefix earlier (in the context of debugging in a web browser, using a url scheme seems more straightforward than the `<internal>` scheme that the node debugger uses). But until the VS Code issue above is fixed, adding the `synode://` prefix will probably create more problems than it fixes.

**Comment by hbenl** [comment] 2017-10-27 10:01
FYI: the VS Code issue has just been fixed, so setting breakpoints should work for all sources opened from the Loaded Scripts Explorer in the latest Insiders build of VS Code.

**Comment by GitStorageOne** [comment] 2017-10-27 10:03
Hello! Great news. Stable version will be released soon as well)

> so setting breakpoints should work for all sources opened from the Loaded Scripts Explorer in the latest Insiders build of VS Code.

Even source mapped?

**Comment by hbenl** [comment] 2017-10-27 10:13
> Even source mapped?

Yes, this should also work (with `"sourceMaps": "client"`).

**Comment by hbenl** [comment] 2018-01-23 18:52
I guess everything is working now.

**Closed by hbenl** 2018-01-23 18:52 UTC
