### ISSUE TITLE
Breakpoints not working with sourceMaps client

### ISSUE THREAD

**Issue by JSteitz** [hbenl/vscode-firefox-debug#69] opened 2018-04-03 18:57 UTC
Breakpoints are not stopping on function calls when we debug with `sourceMaps` set to `client`.

**Browser Version** 59.0.2 (64-bit)
**Webpack Version** 4 (with babel)
**Sourcemaps Type** inline-source-map

Related issues: #62

Here is a repo with a minimal test case. More Information can be found in the Readme.
https://github.com/JSteitz/bug-vscode-firefox-debug-breakpoints-not-working

**Comment by hbenl** [comment] 2018-04-06 16:27
Thanks for the test case, it saved me a lot of time!

This seems to be a Firefox issue that has already been fixed in the nightlies: I could reproduce it in FF 59.0.2 but when I tried with the current developer edition (60.0b10), all breakpoints started working.

**Closed by hbenl** 2018-04-06 16:27 UTC
