### ISSUE TITLE
eval error in the browser's devtools goes to debugger

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#48] opened 2017-09-16 23:18 UTC
![](https://drive.google.com/uc?id=0B-OJBofmehO3UE1qT2luYVU0M2M)
opened browser's devtools, entered a var name that doesn't exist in the console, got a stop in the debugger, tab with the eval and the exception in the inspector. Don't think its by design...

**Comment by hbenl** [comment] 2017-09-17 18:36
> Don't think its by design...

Well, I never designed anything for this situation because I never thought about the possibility of using this debug adapter and the devtools together. What would you expect in this situation? That the exception is shown in the devtools instead? I don't think I can tell Firefox to do that. I think I couldn't even tell (from looking at the information that Firefox gives me about the exception) that the exception was caused by something done in the devtools...

**Comment by Spown** [comment] 2017-09-17 18:50
> What would you expect in this situation?

well, I would expect debugger to ignore it completely. The stack starts with ``@debugger eval`` so you can make it not stop on the exceptions that match this pattern. Probably not by default, but if a specific option is on.

But it's not like it's a critical thing. Or even a thing. Chrome ~~crashes~~ closes silently if you try to open devtools while debugger is running and they maintain it's not a bug. So if you have other things to do - you can just close this issue.

**Comment by Spown** [comment] 2017-09-18 11:01
also, using VSCode's "Debug Evaluate" via context menu does the same, which is much less ok.

**Comment by hbenl** [comment] 2017-09-18 15:13
Hmm, I would have expected "Debug Evaluate" exceptions to be shown in the debugger. But the Node and Chrome debuggers behave the way *you* expected, so I'll change the behaviour in the next release (and possibly offer a config switch in case someone wants to see "Debug Evaluate" exceptions).

**Comment by Spown** [comment] 2017-09-18 22:31
Well, Chrome doesn't ignore it exactly - it outputs the printable representation of the Error in the Debug Console. I cant see why it can't be outputed as expandable object, thoug, but that's beside the point. 

Also a correction to my prev. report: VSCode's "Debug Evaluate" works fine on it's own, but if the same string was input that priviously was used in the FF's Debugger and caused the OP behavior - the VSCode's "Debug Evaluate" would do the same. Evaluating another string, that is expected to produce __another__ error afterwards works fine, ie outputs in the console.

An example:
1. I eval ``map.events.fire('wheel')`` in the Firefox's devtools console. A tab with the string is opened in the VSC, execution is paused, the Error is visible in the VSC inspector. I resume the execution 
2. evaluate the same ``map.events.fire('wheel')`` in the VSC debug console or via context menu. The same happens. I resume the execution
4. evaluate ``map.events.fire('whe'+'el')`` in the VSC debug console. Same thing.
5. evaluate ``map.events.fire('wheel2')`` in the VSC debug console. Doesn't open a tab, doesn't pause and outputs a different output into the VSC's debug console.

It seems that the arrors are cached somewhere internally and cause the same behavior regarding their representation no matter from where they are originated in the future. This may be a deeper problem and not your extension's fault...

**Comment by hbenl** [comment] 2017-09-19 18:47
The reason for this behaviour is that VS Code seems to treat all sources (in this case the scripts entered in Firefox' or VS Code's debugger console) as being the same if I don't give them a name, even if these sources have different numerical IDs. As a result, whenever a script from the debugger console should be shown, VS Code will show the very first such script.
This can easily be fixed, I just have to give these sources a name (I already do this for normal `eval` scripts, but overlooked to do the same for the `debugger eval` scripts).

**Comment by hbenl** [comment] 2017-10-08 11:51
Both issues (skipping exceptions that were triggered from the debug console and giving a name to `debugger eval` scripts) are fixed in version 0.16.1.

**Closed by hbenl** 2017-10-08 11:51 UTC
