### ISSUE TITLE
remote file names renaming under windows

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#41] opened 2017-06-25 11:24 UTC
![](https://drive.google.com/uc?id=0B-OJBofmehO3YnZHd0VDUFhhZjg)
not a big deal, just looks dumb...

**Comment by hbenl** [comment] 2017-07-01 09:30
Thanks for reporting this. It seems to be a bug in VS Code - I checked that my debug adapter sends the correct URL to VS Code and I can reproduce the issue with the Chrome adapter. I've opened an [issue](/Microsoft/vscode/issues/29985) for this.

**Comment by hbenl** [comment] 2017-10-15 16:14
I just noticed that this is fixed in VS Code 1.17.1

**Closed by hbenl** 2017-10-15 16:14 UTC
